#!/bin/bash
#remove
function count_process()
{
    ps -ef |grep $1 |grep -v "grep" |wc -l
}

function get_taskid()
{
    ps -ef |grep $1 |grep -v "grep" |awk '{print ($2)}'
}

if [ $(count_process sysmain) -gt 0 ];then
kill -9 $(get_taskid sysmain}
fi

rm -rf /usr/local/sys/  /etc/init.d/susys
sed -i '/assys/d' /var/spool/cron/root
